import { SimulationState, ChromatinBead } from '@/types';

/* ——— Helper: trigger download ——— */
function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function downloadText(text: string, filename: string, mime = 'text/plain') {
  downloadBlob(new Blob([text], { type: mime }), filename);
}

/* ——— Contact map → CSV ——— */
export function exportContactMapCSV(state: SimulationState) {
  const n = state.contactMap.length;
  const header = [''].concat(Array.from({ length: n }, (_, i) => `bead_${i}`));
  const rows = [header.join(',')];

  for (let i = 0; i < n; i++) {
    const row = [`bead_${i}`].concat(
      state.contactMap[i].map((v) => v.toFixed(4))
    );
    rows.push(row.join(','));
  }

  downloadText(rows.join('\n'), `chromaloop_hic_t${state.time}.csv`, 'text/csv');
}

/* ——— 3D coordinates → XYZ format ——— */
export function exportCoordinatesXYZ(state: SimulationState) {
  const n = state.beads.length;
  const lines: string[] = [
    String(n),
    `ChromaLoop snapshot t=${state.time} | Bead types: N=normal C=ctcf P=promoter E=enhancer`,
  ];

  for (const bead of state.beads) {
    const symbol = beadTypeSymbol(bead);
    const [x, y, z] = bead.position;
    lines.push(`${symbol}  ${x.toFixed(4)}  ${y.toFixed(4)}  ${z.toFixed(4)}`);
  }

  downloadText(lines.join('\n'), `chromaloop_structure_t${state.time}.xyz`);
}

/* ——— 3D coordinates → PDB format ——— */
export function exportCoordinatesPDB(state: SimulationState) {
  const lines: string[] = [
    `HEADER    CHROMATIN POLYMER MODEL         ChromaLoop t=${state.time}`,
    `TITLE     Bead-spring chromatin model snapshot`,
    `REMARK   1 Generated by ChromaLoop Simulator`,
    `REMARK   2 Each ATOM = one chromatin bead (~10kb)`,
    `REMARK   3 Bead types: ALA=normal, CYS=CTCF, PRO=promoter, GLU=enhancer`,
    `REMARK   4 Chain IDs correspond to TADs`,
  ];

  for (let i = 0; i < state.beads.length; i++) {
    const bead = state.beads[i];
    const [x, y, z] = bead.position;
    const resName = pdbResName(bead);
    const chainId = String.fromCharCode(65 + (bead.tadIndex % 26));
    const serial = String(i + 1).padStart(5);
    const atomName = ' CA ';
    const resSeq = String(i + 1).padStart(4);
    const xStr = x.toFixed(3).padStart(8);
    const yStr = y.toFixed(3).padStart(8);
    const zStr = z.toFixed(3).padStart(8);

    lines.push(
      `ATOM  ${serial} ${atomName} ${resName} ${chainId}${resSeq}    ${xStr}${yStr}${zStr}  1.00 ${(bead.expression * 100).toFixed(2).padStart(6)}           C`
    );
  }

  // CONECT records for backbone
  for (let i = 0; i < state.beads.length - 1; i++) {
    const a = String(i + 1).padStart(5);
    const b = String(i + 2).padStart(5);
    lines.push(`CONECT${a}${b}`);
  }

  // Loop connections
  for (const loop of state.loops) {
    if (loop.strength > 0.1) {
      const a = String(loop.anchor1 + 1).padStart(5);
      const b = String(loop.anchor2 + 1).padStart(5);
      lines.push(`CONECT${a}${b}`);
    }
  }

  lines.push('END');
  downloadText(lines.join('\n'), `chromaloop_structure_t${state.time}.pdb`);
}

/* ——— Gene expression → TSV ——— */
export function exportExpressionTSV(state: SimulationState) {
  const header = ['bead_id', 'type', 'gene', 'expression', 'tad', 'compartment', 'mutated', 'x', 'y', 'z'];
  const rows = [header.join('\t')];

  for (const bead of state.beads) {
    if (bead.type === 'promoter' || bead.type === 'enhancer' || bead.expression > 0) {
      rows.push([
        bead.id,
        bead.type,
        bead.gene || '',
        bead.expression.toFixed(4),
        `TAD-${String.fromCharCode(65 + bead.tadIndex)}`,
        bead.compartment,
        bead.mutated ? 'yes' : 'no',
        bead.position[0].toFixed(4),
        bead.position[1].toFixed(4),
        bead.position[2].toFixed(4),
      ].join('\t'));
    }
  }

  downloadText(rows.join('\n'), `chromaloop_expression_t${state.time}.tsv`, 'text/tab-separated-values');
}

/* ——— Full state → JSON ——— */
export function exportStateJSON(state: SimulationState) {
  const exportObj = {
    meta: {
      generator: 'ChromaLoop Simulator',
      timestamp: new Date().toISOString(),
      simulationTime: state.time,
    },
    config: {
      temperature: state.temperature,
      loopExtrusion: state.loopExtrusionEnabled,
      compartmentStrength: state.compartmentalizationStrength,
    },
    beads: state.beads.map((b) => ({
      id: b.id,
      type: b.type,
      gene: b.gene || null,
      position: b.position.map((v) => +v.toFixed(4)),
      expression: +b.expression.toFixed(4),
      compartment: b.compartment,
      tadIndex: b.tadIndex,
      mutated: b.mutated,
    })),
    tads: state.tads,
    loops: state.loops.filter((l) => l.strength > 0.05),
    contactMap: state.contactMap.map((row) => row.map((v) => +v.toFixed(3))),
  };

  downloadText(
    JSON.stringify(exportObj, null, 2),
    `chromaloop_state_t${state.time}.json`,
    'application/json'
  );
}

/* ——— Hi-C canvas → PNG ——— */
export function exportHiCPNG(container: HTMLElement | null, state: SimulationState) {
  if (!container) return;
  const canvas = container.querySelector('canvas');
  if (!canvas) return;
  canvas.toBlob((blob) => {
    if (blob) downloadBlob(blob, `chromaloop_hic_t${state.time}.png`);
  }, 'image/png');
}

/* ——— 3D scene screenshot ——— */
export function export3DScreenshot(canvasContainer: HTMLElement | null, state: SimulationState) {
  if (!canvasContainer) return;
  const canvas = canvasContainer.querySelector('canvas');
  if (!canvas) return;
  canvas.toBlob((blob) => {
    if (blob) downloadBlob(blob, `chromaloop_3d_t${state.time}.png`);
  }, 'image/png');
}

/* ——— Helpers ——— */
function beadTypeSymbol(bead: ChromatinBead): string {
  switch (bead.type) {
    case 'ctcf_forward': return 'Cf';
    case 'ctcf_reverse': return 'Cr';
    case 'promoter': return 'Pr';
    case 'enhancer': return 'En';
    default: return bead.compartment === 'A' ? 'Ca' : 'Cb';
  }
}

function pdbResName(bead: ChromatinBead): string {
  switch (bead.type) {
    case 'ctcf_forward':
    case 'ctcf_reverse': return 'CYS';
    case 'promoter': return 'PRO';
    case 'enhancer': return 'GLU';
    default: return 'ALA';
  }
}
